### ISSUE TITLE
Help for dllcall.

### ISSUE THREAD

**Issue by xx1raven1xx** [agrippa1994/S7-AHK#2]
Sorry for misuse of "Pull Request". I'm new here. And forgive my language, I'm Russian.(translate.google.com my friend)
I'm interested in the correct function call from Snap7.dll.
In particular, I'm interested in how to get data from this function?

```
Int Cli_DBRead (S7Object Client, int DBNumber, int Start, int Size,
    Void * pUsrData);
 
Function Cli_DBRead (Client: S7Object; DBNumber, Start,
    Size: integer; PUsrData: pointer): integer;
```

What is * pUsrData? Pointer to user data. That is, an array with data from DB? How will this be done correctly?
Or here is one more function:
```
Int Cli_GetPlcDateTime (S7Object Client, tm * DateTime);
 
Function Cli_GetPlcDateTime (Client: S7Object;
    Var DateTime: TCPP_tm): integer;
```
Here we get the general time in the incomprehensible structure of TCPP_tm.
In general, I really want to understand all aspects of the correct call to DllCall.

**Comment by xx1raven1xx** [comment]
```
ReadDB(obj, db, start, size){
	VarSetCapacity(data, 10240000, 0)
	DllCall("snap7.dll\Cli_DBRead", "UInt", obj, "Int", db, "int", start, "int", size, "str", data)
	return data
}
```
This is right? 
"str", data Which is correct?
Why do I get this line? 

> B[К«BTНЗBeµ/BB:9B{Т«Aшк9BG)/

**Comment by agrippa1994** [comment]
```
ReadDB(obj, db, start, size){
	VarSetCapacity(data, size, 0)
	DllCall("snap7.dll\Cli_DBRead", "UInt", obj, "Int", db, "int", start, "int", size, "str", data)
	return data
}
```

ReadDB returns binary data encoded in a string. Use [NumGet](https://autohotkey.com/docs/commands/NumGet.htm) to cast it to an integer. Also consider the [Endianness](https://en.wikipedia.org/wiki/Endianness). According to the [official SNAP7 documentation](http://snap7.sourceforge.net/siemens_dataformat.html), S7 uses Big Endian whereas "normal" computers use Little Endian. You will have to convert it manually in AHK

**Comment by xx1raven1xx** [comment]
This is the function that's doing it? Rearranges data back to front?
```
BEint(ByRef Var, ByRef BE, Bytes) {
	VarSetCapacity(BE, Bytes, 0)
	
	loop, %Bytes%
	{
		byte := NumGet(Var, Bytes-A_Index, "UChar")
		NumPut(byte, BE, A_Index-1, "UChar")
		
	}
	
	loop, %Bytes% {
		MsgBox, % NumGet(BE, A_index - 1, "UChar")
	}
}
```

**Comment by agrippa1994** [comment]
This function seems to be correct. There are also some other wrappers for snap7 available, e.g., for NodeJS. Consider to take a look at those wrappers because they need the same logic as here :-)
